#!/usr/local/env bash

#TODO: Make this smarter, autodetect flatpak files

utils::is_cmd flatpak && {
  vic install flatpak bottles
  vic install flatpak discord
  vic install flatpak flatseal
  vic install flatpak slack
  vic install flatpak tidal
  vic install flatpak zoom
  exit
}
