#!/usr/bin/env bash

source ./utils

declare -A skip_on_run=("00_setup")

args() {
  local OPTIND verbose name

  while getopts "h?vn:" opt; do
    case "$opt" in
    h | \?)
      echo "Usage: $0 [-v] [-n name]"
      exit 0
      ;;
    v)
      verbose=1
      ;;
    n)
      name="${OPTARG}"
      ;;
    esac
  done

  shift $((OPTIND - 1))

  [ "${1:-}" = "--" ] && shift

  echo "verbose=$verbose, name='$name', Leftovers: $@"

}

main() {

  utils::path::map_dirs && utils::path::map_files dirs

  utils::path::print_dirs
  utils::path::print_files
}

args "${@}"

# main
