#!/usr/bin/env bash

# Arguments
# Honored Left -> Right [INT] [CMD] [SUB] [SCP] [ARG]
# ie: vic setup dev langs
INT=""
CMD=""
SUB=""
SCP=""
ARG=""

# set HERE to bootstrap to call utils from anywhere
HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

# if called from /usr/local/bin symlink
[[ ! -f "${HERE}"/utils ]] &&
  HERE="$(dirname "$(readlink -f "${0}")")"

export RESOURCES="${HERE}/setup/resources"
export REPOS="${HERE}/repos"

# source utils to use HERE
source "${HERE}"/utils >&2

main() {

  utils::bootstrap

  # [[ ! -z ${@} ]] && utils::exec "${@}"
  [[ -n ${*} ]] && utils::exec "${@}"
}

main "${@}"
