#!/usr/bin/env bash

# set HERE to bootstrap to call utils from anywhere
HERE=$(cd $(dirname "${BASH_SOURCE[0]}") &>/dev/null && pwd)

# if called from /usr/local/bin symlink
[[ ! -f "${HERE}"/utils ]] &&
  HERE="$(dirname "$(readlink -f "${0}")")"

# source utils to use HERE
source "${HERE}"/utils >&2

main() {

  utils::bootstrap

  [[ ! -z ${@} ]] && utils::exec "${@}"
}

main "${@}"
