#!/usr/bin/env bash

# set HERE to bootstrap to call utils from anywhere
HERE=$(cd $(dirname "${BASH_SOURCE[0]}") &>/dev/null && pwd)
source "${HERE}"/utils

source ./utils

#args() {
#  local opts="h"
#  local OPTIND dir cmd
#
#  while getopts "${opts}" opt; do
#    case "$opt" in
#    h)
#      echo "Usage: $0 [-v] [-n name]"
#      exit 0
#      ;;
#    *)
#      dir="${OPTARG}"
#      cmd="${OPTARG}"
#      ;;
#    esac
#  done
#
#  shift $((OPTIND - 1))
#
#  [ "${1:-}" = "--" ] && shift
#
#  echo "verbose=$verbose, dir=${dir}, Leftovers: $@"
#
#}

main() {
  utils::bootstrap

  utils::path::print_lookup

  [[ ! -z ${@} ]] && utils::exec "${@}"
}

main "${@}"
