#!/usr/bin/env bash

# set HERE to bootstrap to call utils from anywhere
HERE=$(cd $(dirname "${BASH_SOURCE[0]}") &>/dev/null && pwd)

[[ ! -f "${HERE}"/utils ]] &&
  HERE="$(dirname "$(readlink -f "${0}")")"

# source utils to use HERE
source "${HERE}"/utils >&2

# source internal commands to use HERE
for f in "${HERE}"/.internal/*; do
  source $f >&2
done

main() {
  utils::bootstrap

  [[ ! -z ${@} ]] && utils::exec "${@}"
}

main "${@}"
