# SSH Server Security Configuration

# Encryption hardening
HostKey /etc/ssh/ssh_host_ed25519_key
HostKeyAlgorithms ssh-ed25519
KexAlgorithms sntrup761x25519-sha512@openssh.com
PubkeyAcceptedKeyTypes ssh-ed25519
Ciphers aes256-gcm@openssh.com
MACs hmac-sha2-256-etm@openssh.com

# Security hardening
AuthenticationMethods publickey
AuthorizedKeysFile .ssh/authorized_keys
Compression no
DisableForwarding yes
LoginGraceTime 15s
MaxAuthTries 3
PermitUserEnvironment no
PermitUserRC no
StrictModes yes
UseDNS no

# Use KeepAlive over SSH instead of with TCP
TCPKeepAlive no
ClientAliveInterval 300
ClientAliveCountMax 3

# Use PAM for session checks
UsePAM yes

# Disable unused authentication methods
ChallengeResponseAuthentication no
GSSAPIAuthentication no
HostbasedAuthentication no
PasswordAuthentication no
PermitRootLogin no
PermitEmptyPasswords no
KbdInteractiveAuthentication no
KerberosAuthentication no

# Information display
Banner /etc/issue.net
PrintLastLog yes
PrintMotd yes
