#!/usr/bin/env bash

# TODO: Add arguments or read ENV vars
# TODO: Add other default git configs
# TODO: SSH key config

git config --global pull.ff only
git config --global user.name "Greg L"
git config --global user.email "gregory.m.laurent@gmail.com"
git config --global init.defaultBranch "main"
