#!/usr/bin/env bash

#TODO: Prompt for y/n personal or default config
#TODO: Personal Config
#TODO: Error handling, check if { vic install extra } has run first

mv ~/.config/nvim{,.bak}

mv ~/.local/share/nvim{,.bak}
mv ~/.local/state/nvim{,.bak}
mv ~/.cache/nvim{,.bak}

git clone https://github.com/LazyVim/starter ~/.config/nvim

rm -rf ~/.config/nvim/.git
