#!/usr/bin/env bash

#TODO: Add input arguments for USER

# $HOME for any user
home=$(utils::user_home)

[[ -d ${home}/.config/nvim ]] && {
  mv "${home}"/.config/nvim{,.bak}
  mv "${home}"/.local/share/nvim{,.bak}
  mv "${home}"/.local/state/nvim{,.bak}
  mv "${home}"/.cache/nvim{,.bak}
}

# git clone https://github.com/LazyVim/starter "${home}/.config/nvim"
# rm -rf "${home}/.config/nvim/.git"

# git clone git@github.com:greglaurent/nvim.git "${home}/.config/nvim"

# setup nodejs package managers
pnpm setup
pnpm install -g neovim
pnpm install -g @mermaid-js/mermaid-cli
