#!/usr/bin/env bash

# TODO: Add input for non-default configuration
utils::is_cmd cargo || {
  pacman -Sy rustup --no-confirm
  # curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

  # . "$HOME/.cargo/env"

  rustup toolchain install
  rustup toolchain install nightly
}

rustup update
rustup toolchain update

cargo install --locked bacon

rustup toolchain install nightly
rustup target add wasm32-unknown-unknown
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

#cargo install --features "clipboard sound"
