#!/usr/bin/env bash

# TODO: Add input for non-default configuration
utils::is_cmd cargo || {
  sudo pacman -S --noconfirm rustup

  rustup install stable
  rustup default stable

  rustup toolchain install
  rustup toolchain install nightly
  rustup target add wasm32-unknown-unknown

  cargo install --locked bacon
  # cargo install --features "clipboard sound"

  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
}

rustup toolchain update

# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
# . "$HOME/.cargo/env"
