#!/usr/bin/env bash

utils::is_root

paru -S --noconfirm qemu virt-manager virt-viewer dnsmasq qemu-desktop libvirt edk2-ovmf \
  vde2 bridge-utils openbsd-netcat ebtables iptables-nft libguestfs swtpm

# Required for looking-glass
paru -S --noconfirm nsis

sudo echo "firewall_backend = \"iptables\"" >>/etc/libvirt/network.conf >/dev/null

#systemctl enable --now libvirtd
usermod -a -G libvirt "$(logname)"

systemctl enable --now libvirtd

virsh net-autostart default
virsh net-start default
