#!/usr/bin/env bash

delete="--delete"
[[ "${1}" = "--force" ]] && delete="-D"

git fetch origin --prune

git branch -vv |
  grep "gone" |
  awk '{print $1}' |
  xargs git branch "${delete}" >&2 ||
  {
    printf '\n%s\n' "[WARN]: Use --force to delete branches." >&2 &&
      printf '%s\n\n' "[WARN]: victor run git prune-local --force." >&2
  }
