#!/usr/bin/env bash

arg="--delete"

[[ "${ARG}" = "--force" ]] && arg="-D"

git switch main

git fetch origin --prune

git branch -vv |
  grep "gone" |
  awk '{print $1}' |
  xargs git branch "${arg}" >&2 ||
  {
    printf '\n%s\n' "[WRN]: Use --force to delete branches." >&2 &&
      printf '%s\n\n' "[WRN]: victor run git prune-local --force." >&2
  }
