#!/usr/bin/env bash

### PARTIAL SCRIPT ######
### REQUIRES PROMPTS ####

output 'Installing the base system (it may take a while).'

# Use linux-firmware-git for better passthrough
pacstrap /mnt base base-devel linux linux-lts linux-headers dkms \
  btrfs-progs e2fsprogs dosfstools xfsprogs nilfs-utils zram-generator \
  acpi lm_sensors fwupd dmraid device-mapper ell \
  grub grub-btrfs efibootmgr \
  snapper snap-pac apparmor \
  networkmanager iptables-nft ufw openssh chrony reflector fail2ban bind nfs-utils wpa_supplicant wireless_tools \
  cups cups-filters cups-pdf \
  pipewire pipewire-audio pipewire-alsa pipewire-pulse pipewire-jack alsa-firmware alsa-plugins alsa-utils wireplumber gst-plugin-pipewire \
  tree curl perl less nano vim man-pages man-db wget diffutils logrotate cronie clang git inotify-tools neovim \
  plymouth xdg-utils xdg-user-dirs accountsservice

# sbctl

CPU=$(grep vendor_id /proc/cpuinfo)
if [[ "${CPU}" == *"AuthenticAMD"* ]]; then
  microcode=amd-ucode
else
  microcode=intel-ucode
fi

pacstrap /mnt "${microcode}"
