#!/usr/bin/env bash

### PARTIAL SCRIPT ######
### REQUIRES PROMPTS ####

## Kernel hardening
#if [ "${use_luks:?}" = '1' ]; then
#  UUID=$(blkid -s UUID -o value "${cryptroot:?}")
#  sed -i "s#quiet#rd.luks.name=${UUID}=cryptroot root=${BTRFS} lsm=landlock,lockdown,yama,integrity,apparmor,bpf mitigations=auto,nosmt spectre_v2=on spectre_bhi=on spec_store_bypass_disable=on tsx=off kvm.nx_huge_pages=force nosmt=force l1d_flush=on spec_rstack_overflow=safe-ret gather_data_sampling=force reg_file_data_sampling=on random.trust_bootloader=off random.trust_cpu=off intel_iommu=on amd_iommu=force_isolation efi=disable_early_pci_dma iommu=force iommu.passthrough=0 iommu.strict=1 slab_nomerge init_on_alloc=1 init_on_free=1 pti=on vsyscall=none ia32_emulation=0 page_alloc.shuffle=1 randomize_kstack_offset=on debugfs=off lockdown=confidentiality module.sig_enforce=1#g" /mnt/etc/default/grub
#else
sed -i "s#quiet#root=${BTRFS} lsm=landlock,lockdown,yama,integrity,apparmor,bpf nowatchdog intel_iommu=on amd_iommu=force_isolation iommu=force iommu.passthrough=0#g" /mnt/etc/default/grub
#fi

## Add keyfile to the initramfs to avoid double password
# if [ "${use_luks}" = '1' ]; then
#   dd bs=512 count=4 if=/dev/random of=/mnt/cryptkey/.root.key iflag=fullblock
#   chmod 000 /mnt/cryptkey/.root.key
#   echo -n "${luks_passphrase:?}" | cryptsetup luksAddKey /dev/disk/by-partlabel/rootfs /mnt/cryptkey/.root.key -d -
#   sed -i 's#FILES=()#FILES=(/cryptkey/.root.key)#g' /mnt/etc/mkinitcpio.conf
#   sed -i "s#module\.sig_enforce=1#module.sig_enforce=1 rd.luks.key=/cryptkey/.root.key#g" /mnt/etc/default/grub
# fi

## Continue kernel hardening
# unpriv cat ./etc/modprobe.d/blacklist.conf | tee /mnt/etc/modprobe.d/blacklist.conf >/dev/null
# unpriv cat ./etc/sysctl.d/99-workstation.conf | tee /mnt/etc/sysctl.d/99-workstation.conf >/dev/null

unpriv cat ./etc/chrony.conf | tee /mnt/etc/chrony.conf >/dev/null

mkdir -p /mnt/etc/sysconfig
unpriv cat ./etc/sysconfig/chronyd | tee /mnt/etc/sysconfig/chronyd >/dev/null

## Remove nullok from system-auth
sed -i 's/nullok//g' /mnt/etc/pam.d/system-auth

## Harden SSH
unpriv cat ./etc/ssh/ssh_config.d/10-custom.conf | tee /mnt/etc/ssh/ssh_config.d/10-custom.conf >/dev/null
unpriv cat ./etc/ssh/sshd_config.d/10-custom.conf | tee /mnt/etc/ssh/sshd_config.d/10-custom.conf >/dev/null

sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /mnt/etc/ssh/sshd_config.d/10-custom.conf

mkdir -p /mnt/etc/systemd/system/sshd.service.d/
unpriv cat ./etc/systemd/system/sshd.service.d/override.conf | tee /mnt/etc/systemd/system/sshd.service.d/override.conf >/dev/null

## Disable coredump
# mkdir -p /mnt/etc/security/limits.d/
# unpriv curl -s ./etc/security/limits.d/30-disable-coredump.conf | tee /mnt/etc/security/limits.d/30-disable-coredump.conf >/dev/null
# mkdir -p /mnt/etc/systemd/coredump.conf.d
# unpriv curl -s ./etc/systemd/coredump.conf.d/disable.conf | tee /mnt/etc/systemd/coredump.conf.d/disable.conf >/dev/null
