#!/usr/bin/env bash

### PARTIAL SCRIPT ######
### REQUIRES PROMPTS ####

## TODO: FIX STATIC PATH ###

## Setup unbound
#if [ "${install_mode}" = 'server' ]; then
#  unpriv curl -s ./etc/unbound/unbound.conf | tee /mnt/etc/unbound/unbound.conf >/dev/null
#fi

## Setup Networking
unpriv cat ./etc/NetworkManager/conf.d/00-random-mac.conf | tee /mnt/etc/NetworkManager/conf.d/00-random-mac.conf >/dev/null

unpriv cat ./etc/NetworkManager/conf.d/01-hostname-mode.conf | tee /mnt/etc/NetworkManager/conf.d/01-hostname-mode.conf >/dev/null

mkdir -p /mnt/etc/sysctl.d/
unpriv cat ./etc/sysctl.d/99-workstation.conf | tee /mnt/etc/sysctl.d/99-workstation.conf >/dev/null

# if [ "${network_daemon}" = 'systemd-networkd' ]; then
#   # arch-iso has working networking, booted does not
#   cp -ap /etc/systemd/network/20* /mnt/etc/systemd/network/ >/dev/null
# fi
