#!/usr/bin/env bash

### PARTIAL SCRIPT ######
### REQUIRES PROMPTS ####

systemctl enable apparmor --root=/mnt
systemctl enable chronyd --root=/mnt
systemctl enable fstrim.timer --root=/mnt
systemctl enable ufw --root=/mnt
systemctl enable fail2ban --root=/mnt
systemctl enable grub-btrfsd.service --root=/mnt
systemctl enable reflector.timer --root=/mnt
systemctl enable snapper-timeline.timer --root=/mnt
systemctl enable snapper-cleanup.timer --root=/mnt
systemctl enable systemd-oomd --root=/mnt
systemctl disable systemd-timesyncd --root=/mnt
systemctl enable NetworkManager --root=/mnt

rm /mnt/etc/resolv.conf
ln -s /run/systemd/resolve/stub-resolv.conf /mnt/etc/resolv.conf
systemctl enable systemd-resolved --root=/mnt
systemctl enable sshd --root=/mnt

# zram-generator just needs this file to start
unpriv cat ./etc/systemd/zram-generator.conf | tee /mnt/etc/systemd/zram-generator.conf >/dev/null
