#!/usr/bin/env bash

set -eu

# Secure boot enrollment
sudo sbctl enroll-keys
sudo sbctl sign /boot/efi/EFI/GRUB/grubx64.efi

sudo firewall-cmd --set-default-zone=block
sudo firewall-cmd --permanent --add-service=dhcpv6-client
sudo firewall-cmd --reload
sudo firewall-cmd --lockdown-on
