#!/usr/bin/env bash

#TODO: Add input arguments for USER

# $HOME for any user
home=$(utils::user_home)

paru -Sy --noconfirm neovim lazygit clang \
  hererocks luarocks \
  nodejs npm pnpm

[[ -d ${home}/.config/nvim ]] && {
  mv "${home}"/.config/nvim{,.bak}
  mv "${home}"/.local/share/nvim{,.bak}
  mv "${home}"/.local/state/nvim{,.bak}
  mv "${home}"/.cache/nvim{,.bak}
}

git clone https://github.com/LazyVim/starter "${home}/.config/nvim"

rm -rf "${home}/.config/nvim/.git"
