#!/usr/bin/env bash

utils::is_root

gpu="0000:03:00.0"

gpu_vd="$(cat /sys/bus/pci/devices/$gpu/vendor) $(cat /sys/bus/pci/devices/$gpu/device)"

function unbind_vfio {
  echo "$gpu_vd" >"/sys/bus/pci/drivers/vfio-pci/remove_id"
  echo 1 >"/sys/bus/pci/devices/$gpu/remove"
  echo 1 >"/sys/bus/pci/rescan"

  echo "Unbound from VFIO"
}

unbind_vfio
