#!/usr/bin/env bash

# TODO: Add missing core packages

utils::is_root

paru -Sy --noconfirm \
  dkms \
  linux-firmware \
  mkinitcpio-firmware \
  linux-headers \
  lm_sensors \
  cups \
  git \
  flatpak \
  fd \
  fzf \
  lazygit \
  ripgrep \
  neovim \
  wl-clipboard \
  kitty \
  wezterm \
  vlc \
  mpv \
  yq

#. "${HERE}/setup/nerd-fonts"
#. "${HERE}/setup/pacman"
