#!/usr/bin/env bash

# TODO: Add missing core packages

paru -Sy --noconfirm \
  dkms \
  linux-firmware \
  linux-headers \
  lm_sensors \
  cups \
  git \
  flatpak \
  fd \
  fzf \
  ripgrep \
  neovim \
  wl-clipboard \
  kitty \
  wezterm \
  vlc \
  mpv \
  yq

. "${HERE}/setup/nerd-fonts"
. "${HERE}/setup/pacman"
