#!/usr/bin/env bash

# TODO: Add missing core packages

paru -Sy --noconfirm \
  dkms \
  linux-firmware \
  linux-headers \
  lm_sensors \
  git \
  fd \
  fzf \
  ripgrep \
  neovim \
  wl-clipboard \
  lua \
  luarocks \
  yq \
  python \
  python-pip \
  python-pynvim \
  nodejs \
  npm \
  pnpm \
  uv
