#!/usr/bin/env bash

# pacstrap /mnt flatpak plasma-meta sddm zsh \
#   kitty wezterm

paru -S --noconfirm libappindicator-gtk3 libdbusmenu-glib libdbusmenu-gtk3 \
  plasma-meta sddm \
  cosmic
#gnome gnome-xtra

sudo systemctl enable sddm
