#!/usr/bin/env bash

paru -Sy --noconfirm \
  lua \
  luarocks \
  python \
  python-pip \
  python-pynvim \
  uv \
  nodejs \
  npm \
  pnpm \
  prettierd \
  typescript \
  typescript-language-server \
  vscode-langservers-extracted \
  tailwindcss-language-server \
  visual-studio-code-bin

. "${HERE}/setup/dev/git"
. "${HERE}/setup/dev/rust"
. "${HERE}/setup/dev/neovim"
