#!/usr/bin/env bash

paru -S --noconfirm \
  mkinitcpio-firmware \
  nushell \
  flameshot \
  obsidian \
  obs-studio \
  cameractrls \
  inkscape \
  vivaldi \
  vivaldi-ffmpeg-codecs \
  zen-browser-bin \
  wl-clipboard \
  kitty \
  wezterm \
  vlc \
  mpv \
  yq \
  flatpak \
  fd \
  fzf \
  lazygit \
  ripgrep \
  snapper-gui \
  tmux \
  kitty \
  wezterm
