#!/usr/bin/env bash

paru -Sy --noconfirm \
  nushell \
  flameshot \
  mkinitcpio-firmware \
  obsidian \
  obs-studio \
  cameractrls \
  inkscape \
  vivaldi \
  vivaldi-ffmpeg-codecs \
  zen-browser-bin \
  slack-desktop \
  zoom \
  wl-clipboard \
  kitty \
  wezterm \
  vlc \
  mpv \
  yq \
  flatpak \
  fd \
  fzf \
  lazygit \
  ripgrep \ 
  snapper-gui \
  cosmic
