#!/usr/bin/env bash

#TODO: AccountsService
paru -S --noconfirm \
  accountsservice \
  awesome-terminal-fonts \
  btrfs-assistant \
  cameractrls \
  cpupower \
  fd \
  flameshot \
  flatpak \
  fzf \
  graphicsmagick \
  imagemagick \
  inkscape \
  kitty \
  kitty \
  lazygit \
  mkinitcpio-firmware \
  mpv \
  nushell \
  obsidian \
  obs-studio \
  ripgrep \
  snapper-gui \
  tealdeer
  tmux \
  vivaldi \
  vivaldi-ffmpeg-codecs \
  vlc \
  wezterm \
  wezterm \
  wl-clipboard \
  yq \
  zen-browser-bin \
