#!/usr/bin/env bash

# Extra utils
paru -S --noconfirm \
  mkinitcpio-firmware \
  lib32-pipewire \
  btrfs-assistant \
  modemmanager

# Extra apps
paru -S --noconfirm \
  awesome-terminal-fonts \
  cameractrls \
  flameshot \
  inkscape \
  just \
  kitty \
  lazygit \
  nushell \
  obsidian \
  obs-studio \
  snapper-gui \
  vivaldi \
  vivaldi-ffmpeg-codecs \
  wezterm \
  zen-browser-bin

#TODO: AccountsService

#TODO: Smart Cards
#https://wiki.archlinux.org/title/Smartcards
# pcsclite \
# ccid \
# opensc \

# rebuild-detector \
