#!/usr/bin/env bash

# neovim package installed with core
paru -Sy --noconfirm lazygit clang \
  hererocks luarocks \
  nodejs npm pnpm

mv ~/.config/nvim{,.bak}
mv ~/.local/share/nvim{,.bak}
mv ~/.local/state/nvim{,.bak}
mv ~/.cache/nvim{,.bak}

git clone https://github.com/LazyVim/starter ~/.config/nvim

rm -rf ~/.config/nvim/.git
