#!/usr/bin/env bash

utils::is_root

pacman-key --init
pacman-key --populate

pacman -Syyu --noconfirm

# Desktop
pacman -S packagekit libpackagekit-glib accountsservice flatpak poppler \
  gutenprint foomatic-db foomatic-db-engine foomatic-db-gutenprint-ppds \
  foomatic-db-nonfree foomatic-db-nonfree-ppds foomatic-db-ppds \
  mpv vlc gstreamer gstreamer-vaapi \
  system-config-printer splix hplip \
  pastel imagemagick graphicsmagick \
  egl-wayland wl-clipboard gtk3 gtksourceview3 xdg-desktop-portal \
  power-profiles-daemon \
  python python-dbus python-gobject python-setuptools \
  pipewire pipewire-audio pipewire-alsa pipewire-pulse pipewire-jack \
  alsa-firmware alsa-plugins alsa-utils wireplumber gst-plugin-pipewire pavucontrol \
  s-nail fd fzf tmux yq ripgrep zsh

# Set firewall
ufw limit 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw default deny incoming
ufw default allow outgoing
ufw enable
