#!/usr/bin/env bash

utils::is_root

pacman-key --init
pacman-key --populate

pacman -Syyu --noconfirm

# Set firewall
ufw limit 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw default deny incoming
ufw default allow outgoing
ufw enable
