#!/usr/bin/env bash

gf="google-fonts"
path="${HERE}/repos"
nf_path="${path}/nerd-fonts"
gf_path="${path}/${gf}"

# Nerd Fonts
rm -rf "${nf_path}" >&2
git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git "${nf_path}"

"${nf_path}/install.sh"

# Google Fonts
wgeturl="https://github.com/google/fonts/archive/main.tar.gz"

mkdir -p "${gf_path}"
echo "Connecting to Github server to download fonts..."
wget "${wgeturl}" -O "${gf_path}/fonts.tar.gz"

echo "Extracting the downloaded archive..."
tar -zxvf "${gf_path}/fonts.tar.gz" -C "${gf_path}"

echo "Creating the /usr/share/fonts/truetype/${gf} folder"
sudo mkdir -p "/usr/share/fonts/truetype/${gf}"

echo "Installing all .ttf fonts in /usr/share/fonts/truetype/${gf}"
find "${gf_path}/fonts-main/" -name "*.ttf" -exec sudo install -m644 {} /usr/share/fonts/truetype/google-fonts/ \; || echo "An error occured, please run this script again."

# Cache fonts locally
echo "Updating the font cache"
fc-cache -f

#TODO: Delete the tarball
