#!/usr/bin/env bash

utils::is_root

# dir="${RESOURCES}/pacman"

# Added copy to install -- no longer needed
#  cp "${dir}/pacman.conf" /etc/pacman.conf

pacman-key --init
pacman-key --populate

pacman -Syyu --noconfirm

cp "${dir}/vconsole.conf" /etc/vconsole.conf
