#!/usr/bin/env bash

utils::is_root

dir="${RESOURCES}/pacman"

cp "${dir}/pacman.conf" /etc/pacman.conf
cp "${dir}/paru.conf" /etc/paru.conf

pacman-key --init
pacman-key --populate

pacman -Syyu

cp "${dir}/vconsole.conf" /etc/vconsole.conf
