#!/usr/bin/env bash

dir="${REPOS}/paru"

utils::is_cmd paru || {
  # sudo pacman -S --needed base-devel
  [[ ! -d $dir ]] &&
    git clone https://aur.archlinux.org/paru.git "${dir}"

  cd "${dir}"
  makepkg -si

  sudo cp "${RESOURCES}/pacman/paru.conf /etc/paru.conf"
