#!/usr/bin/env bash

utils::is_root

pacman -Syyu

# Secure boot enrollment
sbctl enroll-keys
sbctl sign /boot/efi/EFI/GRUB/grubx64.efi

# Set firewall
ufw limit 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw default deny incoming
ufw default allow outgoing
ufw enable

vic setup pacman

# user="$(logname)"
# sudo --user "${user}" bash <<HereTag
# echo "[MSG] VICTOR running post-install as: ${user}"
# vic setup user-env
# HereTag

# pacman -Sy plasma-meta sddm \
#   zsh flatpak fzf lazygit ripgrep wl-clipboard kitty wezterm \
# vlc mpv yq
#
# pacman -Sy plasma-meta sddm \
#   zsh fzf lazygit ripgrep wl-clipboard kitty wezterm \
# vlc mpv yq
#
# systemctl enable sddm
