#!/usr/bin/env bash

utils::is_root

vic setup pacman

# Secure boot enrollment
# sbctl enroll-keys
# sbctl sign /boot/efi/EFI/GRUB/grubx64.efi

# Installed via pacstrap
#vic install core

vic install amd
vic setup virt

# Set firewall
ufw limit 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw default deny incoming
ufw default allow outgoing
ufw enable
