#!/usr/bin/env bash

paru -S --noconfirm qemu virt-manager virt-viewer dnsmasq \
  vde2 bridge-utils openbsd-netcat ebtables iptables-nft libguestfs

#TODO: Confirm firewall isn't an issue
# sudo echo "firewall_backend = \"iptables\"" >>/etc/libvirt/network.conf >/dev/null

#systemctl enable --now libvirtd
usermod -aG libvirt "$(logname)"
systemctl enable --now libvirtd
