#!/usr/env/bin bash

utils::is_root

sudo pacman -S --noconfirm sbctl
sudo sbctl create-keys
sudo mkinitcpio -P

# Install new grub version
sudo grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB --disable-shim-lock

# Sign grub
sudo sbctl sign-all

# Disable root subvol pinning.
## This is **extremely** important, as snapper expects to be able to set the default btrfs subvol.
# shellcheck disable=SC2016
sudo sed -i 's/rootflags=subvol=${rootsubvol}//g' /mnt/etc/grub.d/10_linux
# shellcheck disable=SC2016
sudo sed -i 's/rootflags=subvol=${rootsubvol}//g' /mnt/etc/grub.d/20_linux_xen

# Generate grub config
sudo grub-mkconfig -o /boot/grub/grub.cfg
